import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  Length,
  IsBoolean,
  IsObject,
} from 'class-validator';
import { Type } from 'class-transformer';
import { IsUnique } from '@shared/validators';
import { DomainTranslationDto } from '@shared/dtos';

export class DomainCreateRequestDto {
  @ApiProperty({
    description: 'Unique code of the domain (auto-generated, do not send on create/update)',
    example: '1',
    minLength: 1,
    maxLength: 10,
    type: String,
    readOnly: true,
    required: false,
  })
  // code is auto-generated by backend, do not send from client
  code?: string;

  @ApiProperty({
    description: 'Name of the domain',
    example: 'Public Health',
    minLength: 1,
    maxLength: 100,
    type: String,
  })
  @IsNotEmpty({ message: 'validation.name.isNotEmpty' })
  @IsString({ message: 'validation.name.isString' })
  @Length(1, 100, { message: 'validation.name.length args: 1,100' })
  @IsUnique(
    { tableName: 'domains', columns: ['name'] },
    { message: 'validation.name.isUnique' },
  )
  @Type(() => String)
  name: string;

  @ApiProperty({
    description: 'Description of the domain',
    example: 'Domain covering public health initiatives',
    minLength: 1,
    maxLength: 500,
    type: String,
  })
  @IsNotEmpty({ message: 'validation.description.isNotEmpty' })
  @IsString({ message: 'validation.description.isString' })
  @Length(1, 500, { message: 'validation.description.length args: 1,500' })
  @Type(() => String)
  description: string;

  @ApiProperty({
    description: 'Translations for the domain. The code field inside each language is auto-generated and read-only.',
    example: {
      en: {
        name: 'Public Health',
        description: 'Domain covering public health initiatives',
        code: '1'
      },
      fr: {
        name: 'Santé Publique',
        description: 'Domaine couvrant les initiatives de santé publique',
        code: '1'
      }
    },
    type: Object,
    required: true,
  })
  @IsNotEmpty({ message: 'validation.translations.isNotEmpty' })
  @IsObject({ message: 'validation.translations.isObject' })
  @Type(() => Object)
  translations: Record<string, DomainTranslationDto>;
}
