import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  Length,
  IsUUID,
  IsOptional,
  IsObject,
  IsNotEmpty,
} from 'class-validator';
import { Type } from 'class-transformer';
import { SubComponentTranslationDto } from '@shared/dtos';
import { IsExists, IsUnique } from '@shared/validators';

export class SubComponentUpdateRequestDto {
  @ApiProperty({
    description: 'ID of the Sub Component',
    example: '123e4567-e89b-12d3-a456-426614174000',
    type: String,
  })
  @IsNotEmpty({ message: 'validation.id.isNotEmpty' })
  @IsString({ message: 'validation.id.isString' })
  @Type(() => String)
  id: string;

  @ApiProperty({
    description: 'Unique code of the sub-component (auto-generated, do not send on update)',
    example: '1.1.1',
    minLength: 1,
    maxLength: 50,
    type: String,
    readOnly: true,
    required: false,
  })
  // code is auto-generated by backend, do not send from client
  @IsOptional()
  @IsString({ message: 'validation.code.isString' })
  @Length(1, 50, { message: 'validation.code.length args: min:1 | max:50' })
  @IsUnique(
    { tableName: 'sub_components', columns: ['code'], exclude: 'id' },
    { message: 'validation.code.isUnique' },
  )
  @Type(() => String)
  code?: string;

  @ApiPropertyOptional({
    description: 'Name of the sub-component',
    example: 'Vaccine Distribution',
    minLength: 1,
    maxLength: 100,
    type: String,
  })
  @IsOptional()
  @IsString({ message: 'validation.name.isString' })
  @Length(1, 100, { message: 'validation.name.length args: min:1 | max:100' })
  @Type(() => String)
  name?: string;

  @ApiPropertyOptional({
    description: 'Description of the sub-component',
    example: 'Sub-component for vaccine distribution',
    minLength: 1,
    maxLength: 500,
    type: String,
  })
  @IsOptional()
  @IsString({ message: 'validation.description.isString' })
  @Length(1, 500, {
    message: 'validation.description.length args: min:1 | max:500',
  })
  @Type(() => String)
  description?: string;

  @ApiPropertyOptional({
    description: 'ID of the associated component',
    example: '123e4567-e89b-12d3-a456-426614174000',
    type: String,
  })
  @IsOptional()
  @IsUUID('4', { message: 'validation.componentId.isUUID' })
  @IsExists(
    { tableName: 'components', columns: ['id'] },
    { message: 'validation.componentId.isExists' },
  )
  @Type(() => String)
  componentId?: string;

  @ApiPropertyOptional({
    description: 'Translations for the sub-component. The code field inside each language is auto-generated and read-only.',
    example: {
      en: {
        name: 'Vaccine Distribution',
        description: 'Sub-component for vaccine distribution',
        code: '1.1.1'
      },
      fr: {
        name: 'Distribution de vaccins',
        description: 'Sous-composant pour la distribution de vaccins',
        code: '1.1.1'
      }
    },
    type: Object,
  })
  @IsOptional()
  @IsObject({ message: 'validation.translations.isObject' })
  @Type(() => Object)
  translations?: Record<string, SubComponentTranslationDto>;
}
