import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  Length,
  IsUUID,
  IsObject,
} from 'class-validator';
import { Type } from 'class-transformer';
import { SubComponentTranslationDto } from '@shared/dtos';
import { IsExists, IsUnique } from '@shared/validators';

export class SubComponentCreateRequestDto {
  @ApiProperty({
    description: 'Unique code of the sub-component (auto-generated, do not send on create/update)',
    example: '1.1.1',
    minLength: 1,
    maxLength: 50,
    type: String,
    readOnly: true,
    required: false,
  })
  // code is auto-generated by backend, do not send from client
  code?: string;

  @ApiProperty({
    description: 'Name of the sub-component',
    example: 'Vaccine Distribution',
    minLength: 1,
    maxLength: 100,
    type: String,
  })
  @IsNotEmpty({ message: 'validation.name.isNotEmpty' })
  @IsString({ message: 'validation.name.isString' })
  @Length(1, 100, { message: 'validation.name.length args: min:1 | max:100' })
  @Type(() => String)
  name: string;

  @ApiProperty({
    description: 'Description of the sub-component',
    example: 'Sub-component for vaccine distribution',
    minLength: 1,
    maxLength: 1000,
    type: String,
  })
  @IsNotEmpty({ message: 'validation.description.isNotEmpty' })
  @IsString({ message: 'validation.description.isString' })
  @Length(1, 1000, {
    message: 'validation.description.length args: min:1 | max:1000',
  })
  @Type(() => String)
  description: string;

  @ApiProperty({
    description: 'ID of the associated component',
    example: '123e4567-e89b-12d3-a456-426614174000',
    type: String,
  })
  @IsNotEmpty({ message: 'validation.componentId.isNotEmpty' })
  @IsUUID('4', { message: 'validation.componentId.isUUID' })
  @IsExists(
    { tableName: 'components', columns: ['id'] },
    { message: 'validation.componentId.isExists' },
  )
  @Type(() => String)
  componentId: string;

  @ApiProperty({
    description: 'Translations for the sub-component. The code field inside each language is auto-generated and read-only.',
    example: {
      en: {
        name: 'Vaccine Distribution',
        description: 'Sub-component for vaccine distribution',
        code: '1.1.1'
      },
      fr: {
        name: 'Distribution de vaccins',
        description: 'Sous-composant pour la distribution de vaccins',
        code: '1.1.1'
      }
    },
    type: Object,
    required: true,
  })
  @IsNotEmpty({ message: 'validation.translations.isNotEmpty' })
  @IsObject({ message: 'validation.translations.isObject' })
  @Type(() => Object)
  translations: Record<string, SubComponentTranslationDto>;
}

