import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1746707276183 implements MigrationInterface {
    name = 'Migration1746707276183'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying NOT NULL, "action" character varying(64) NOT NULL, "subject" character varying(64) NOT NULL, "description" text NOT NULL, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(64) NOT NULL, "description" text NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "responses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "assessmentId" character varying NOT NULL, "content" character varying NOT NULL, "comments" jsonb, "isPublished" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_be3bdac59bd243dff421ad7bf70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assessment_members_role_enum" AS ENUM('team_leader', 'primary', 'secondary')`);
        await queryRunner.query(`CREATE TABLE "assessment_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "assessmentId" uuid NOT NULL, "groupName" character varying NOT NULL, "role" "public"."assessment_members_role_enum" NOT NULL, CONSTRAINT "REL_37ee2e3555f4d4d7da2ec2998e" UNIQUE ("userId"), CONSTRAINT "PK_d0a742094c8e4fa91046f19a86c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37ee2e3555f4d4d7da2ec2998e" ON "assessment_members" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d50cfe323c72819e9b520ac627" ON "assessment_members" ("assessmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d50cfe323c72819e9b520ac627" ON "assessment_members" ("assessmentId") `);
        await queryRunner.query(`CREATE TABLE "scales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "measurementId" uuid NOT NULL, "rate" integer NOT NULL, CONSTRAINT "PK_1609bff97353a75ffa9916f8e65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "measurement_scale_descriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "subComponentId" uuid NOT NULL, "measurementId" uuid NOT NULL, "description" text NOT NULL, CONSTRAINT "PK_50b824ac9e8157ed264f3220c41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c85013226083add8b763cb776" ON "measurement_scale_descriptions" ("subComponentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e169341ffba51be4b4c9466f8b" ON "measurement_scale_descriptions" ("measurementId") `);
        await queryRunner.query(`CREATE TABLE "measurements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying NOT NULL, "description" character varying NOT NULL, "color" character varying NOT NULL, "rate" integer NOT NULL, CONSTRAINT "PK_3c0e7812563f27fd68e8271661b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roadmaps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "answerId" uuid NOT NULL, "subComponentId" uuid NOT NULL, "measurementId" uuid NOT NULL, "target" character varying NOT NULL, "activities" character varying NOT NULL, "responsible" character varying NOT NULL, "resources" character varying NOT NULL, "documentation" character varying NOT NULL, "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, CONSTRAINT "PK_9b0d527f9c64d15405c21e7ca54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8029a1a5348e1af2ab284f2237" ON "roadmaps" ("answerId") `);
        await queryRunner.query(`CREATE TABLE "answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "assessmentId" uuid NOT NULL, "userId" uuid NOT NULL, "groupName" character varying NOT NULL, "subComponentId" uuid NOT NULL, "measurementId" uuid NOT NULL, "rate" integer NOT NULL, "notes" text, "evidence" jsonb NOT NULL, "reference" jsonb NOT NULL, CONSTRAINT "REL_1bd66b7e0599333e61d2e3e167" UNIQUE ("userId"), CONSTRAINT "REL_03d6ca091fc6902430e48d4b3e" UNIQUE ("subComponentId"), CONSTRAINT "REL_e0243bcb1acde5e1a8527b9d93" UNIQUE ("measurementId"), CONSTRAINT "PK_9c32cec6c71e06da0254f2226c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_863462f942e7c32f90bc411617" ON "answers" ("assessmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_863462f942e7c32f90bc411617" ON "answers" ("assessmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1bd66b7e0599333e61d2e3e167" ON "answers" ("userId") `);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "assessmentId" uuid NOT NULL, "groupName" character varying, "userId" uuid NOT NULL, "content" text NOT NULL, "isFinal" boolean NOT NULL DEFAULT false, "domainId" uuid, CONSTRAINT "REL_bed415cd29716cd707e9cb3c09" UNIQUE ("userId"), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bed415cd29716cd707e9cb3c09" ON "reports" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5dec0f90b2df8ac2a78dc3ffa6" ON "reports" ("domainId") `);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying NOT NULL, "email" character varying NOT NULL, "assessmentId" character varying NOT NULL, "groupName" character varying NOT NULL, "role" character varying NOT NULL, "token" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assessments_language_enum" AS ENUM('en', 'fr', 'ar', 'sw')`);
        await queryRunner.query(`CREATE TABLE "assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "country" character varying NOT NULL, "date" TIMESTAMP NOT NULL, "language" "public"."assessments_language_enum" NOT NULL DEFAULT 'en', "domainId" uuid, CONSTRAINT "REL_a6aab0d30090866bb9cc0c61c7" UNIQUE ("userId"), CONSTRAINT "PK_a3442bd80a00e9111cefca57f6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6aab0d30090866bb9cc0c61c7" ON "assessments" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_90b881aab6a38f217baeb8f368" ON "assessments" ("domainId") `);
        await queryRunner.query(`CREATE TABLE "assessment_sub_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "assessmentId" uuid NOT NULL, "subComponentId" uuid NOT NULL, CONSTRAINT "PK_ab40c42e00999e7d41513c9c6e6" PRIMARY KEY ("id", "assessmentId", "subComponentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8872c355bac08350b10674213" ON "assessment_sub_components" ("assessmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_491f914eb689f85dacb625ec36" ON "assessment_sub_components" ("subComponentId") `);
        await queryRunner.query(`CREATE TABLE "sub_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "maxScore" integer, "componentId" uuid, CONSTRAINT "UQ_3f78a1f320640def3b4c2d98b1d" UNIQUE ("code"), CONSTRAINT "PK_d403367627d1958909a22da2ef5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_520ce9d3c21e8c923594e41a9b" ON "sub_components" ("componentId") `);
        await queryRunner.query(`CREATE TABLE "components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "domainId" uuid, CONSTRAINT "UQ_5409124de81d8d24ef76b4a5315" UNIQUE ("code"), CONSTRAINT "PK_0d742661c63926321b5f5eac1ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ee9fc4c57cce74443dca8d033" ON "components" ("domainId") `);
        await queryRunner.query(`CREATE TABLE "domains" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_c1eacbd811cc699e0854b4090e1" UNIQUE ("code"), CONSTRAINT "PK_05a6b087662191c2ea7f7ddfc4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."dashboard_assessmentstatus_enum" AS ENUM('planned', 'in_progress', 'completed', 'no_data')`);
        await queryRunner.query(`CREATE TABLE "dashboard" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "country" character varying NOT NULL, "assessmentStatus" "public"."dashboard_assessmentstatus_enum" NOT NULL, "externalReport" text, CONSTRAINT "PK_233ed28fa3a1f9fbe743f571f75" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."profiles_gender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "title" character varying NOT NULL, "firstName" character varying(64) NOT NULL, "lastName" character varying(64) NOT NULL, "email" character varying(320), "gender" "public"."profiles_gender_enum", "dateOfBirth" date, "country" character varying(100), "jobTitle" character varying, "status" character varying, CONSTRAINT "UQ_5b49bd22c967ce2829ca8f17720" UNIQUE ("email"), CONSTRAINT "REL_315ecd98bd1a42dcf2ec4e2e98" UNIQUE ("userId"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "isAdmin" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "disabled" boolean NOT NULL DEFAULT false, "disabledAt" TIMESTAMP WITH TIME ZONE, "status" "public"."users_status_enum" NOT NULL DEFAULT 'inactive', "lastLoggedInAt" TIMESTAMP WITH TIME ZONE, "lastPasswordUpdatedAt" TIMESTAMP WITH TIME ZONE, "lang" character varying(4) NOT NULL DEFAULT 'en', "refreshToken" character varying, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions_users_users" ("permissionsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_9afd76fbb1b7b9e72bcfb72e957" PRIMARY KEY ("permissionsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28ed803df963293de68d58e191" ON "permissions_users_users" ("permissionsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_79318fb026bf8e2a19a5f64d41" ON "permissions_users_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "roles_permissions" ("rolesId" uuid NOT NULL, "permissionsId" uuid NOT NULL, CONSTRAINT "PK_f8e26259e2114a037f1180ec0d8" PRIMARY KEY ("rolesId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bf98d8fd47610db71dfc5a4a5f" ON "roles_permissions" ("rolesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f25fd350775094ceb3a02c1468" ON "roles_permissions" ("permissionsId") `);
        await queryRunner.query(`CREATE TABLE "users_roles" ("usersId" uuid NOT NULL, "rolesId" uuid NOT NULL, CONSTRAINT "PK_37623035dbbec2f0a4b76ff4000" PRIMARY KEY ("usersId", "rolesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_deeb1fe94ce2d111a6695a2880" ON "users_roles" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_21db462422f1f97519a29041da" ON "users_roles" ("rolesId") `);
        await queryRunner.query(`CREATE TABLE "users_permissions_permissions" ("usersId" uuid NOT NULL, "permissionsId" uuid NOT NULL, CONSTRAINT "PK_b134646ad8acb7a41ef766c4ca3" PRIMARY KEY ("usersId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b70d6dbde0e342b2afd199490c" ON "users_permissions_permissions" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f417b3a2e38339487716aa0742" ON "users_permissions_permissions" ("permissionsId") `);
        await queryRunner.query(`ALTER TABLE "assessment_members" ADD CONSTRAINT "FK_37ee2e3555f4d4d7da2ec2998ed" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_members" ADD CONSTRAINT "FK_d50cfe323c72819e9b520ac6273" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scales" ADD CONSTRAINT "FK_85bcf18557499c631fe04a38259" FOREIGN KEY ("measurementId") REFERENCES "measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measurement_scale_descriptions" ADD CONSTRAINT "FK_8c85013226083add8b763cb776d" FOREIGN KEY ("subComponentId") REFERENCES "sub_components"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measurement_scale_descriptions" ADD CONSTRAINT "FK_e169341ffba51be4b4c9466f8ba" FOREIGN KEY ("measurementId") REFERENCES "measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roadmaps" ADD CONSTRAINT "FK_8029a1a5348e1af2ab284f2237f" FOREIGN KEY ("answerId") REFERENCES "answers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roadmaps" ADD CONSTRAINT "FK_bf403fa995741d8fdab78c60b18" FOREIGN KEY ("subComponentId") REFERENCES "sub_components"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roadmaps" ADD CONSTRAINT "FK_1654cfbc9ae5de0ea9d0789e51b" FOREIGN KEY ("measurementId") REFERENCES "measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_863462f942e7c32f90bc411617f" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_1bd66b7e0599333e61d2e3e1678" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_03d6ca091fc6902430e48d4b3ec" FOREIGN KEY ("subComponentId") REFERENCES "sub_components"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_e0243bcb1acde5e1a8527b9d934" FOREIGN KEY ("measurementId") REFERENCES "measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_b48a96c0b32fd72836304e87808" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_bed415cd29716cd707e9cb3c09c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_5dec0f90b2df8ac2a78dc3ffa65" FOREIGN KEY ("domainId") REFERENCES "domains"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_a6aab0d30090866bb9cc0c61c72" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_90b881aab6a38f217baeb8f368c" FOREIGN KEY ("domainId") REFERENCES "domains"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_sub_components" ADD CONSTRAINT "FK_b8872c355bac08350b10674213e" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_sub_components" ADD CONSTRAINT "FK_491f914eb689f85dacb625ec36d" FOREIGN KEY ("subComponentId") REFERENCES "sub_components"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_components" ADD CONSTRAINT "FK_520ce9d3c21e8c923594e41a9b4" FOREIGN KEY ("componentId") REFERENCES "components"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "components" ADD CONSTRAINT "FK_4ee9fc4c57cce74443dca8d0330" FOREIGN KEY ("domainId") REFERENCES "domains"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions_users_users" ADD CONSTRAINT "FK_28ed803df963293de68d58e191f" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "permissions_users_users" ADD CONSTRAINT "FK_79318fb026bf8e2a19a5f64d411" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles_permissions" ADD CONSTRAINT "FK_bf98d8fd47610db71dfc5a4a5ff" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "roles_permissions" ADD CONSTRAINT "FK_f25fd350775094ceb3a02c14681" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_roles" ADD CONSTRAINT "FK_deeb1fe94ce2d111a6695a2880e" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_roles" ADD CONSTRAINT "FK_21db462422f1f97519a29041da0" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_permissions_permissions" ADD CONSTRAINT "FK_b70d6dbde0e342b2afd199490cc" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_permissions_permissions" ADD CONSTRAINT "FK_f417b3a2e38339487716aa0742a" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users_permissions_permissions" DROP CONSTRAINT "FK_f417b3a2e38339487716aa0742a"`);
        await queryRunner.query(`ALTER TABLE "users_permissions_permissions" DROP CONSTRAINT "FK_b70d6dbde0e342b2afd199490cc"`);
        await queryRunner.query(`ALTER TABLE "users_roles" DROP CONSTRAINT "FK_21db462422f1f97519a29041da0"`);
        await queryRunner.query(`ALTER TABLE "users_roles" DROP CONSTRAINT "FK_deeb1fe94ce2d111a6695a2880e"`);
        await queryRunner.query(`ALTER TABLE "roles_permissions" DROP CONSTRAINT "FK_f25fd350775094ceb3a02c14681"`);
        await queryRunner.query(`ALTER TABLE "roles_permissions" DROP CONSTRAINT "FK_bf98d8fd47610db71dfc5a4a5ff"`);
        await queryRunner.query(`ALTER TABLE "permissions_users_users" DROP CONSTRAINT "FK_79318fb026bf8e2a19a5f64d411"`);
        await queryRunner.query(`ALTER TABLE "permissions_users_users" DROP CONSTRAINT "FK_28ed803df963293de68d58e191f"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985"`);
        await queryRunner.query(`ALTER TABLE "components" DROP CONSTRAINT "FK_4ee9fc4c57cce74443dca8d0330"`);
        await queryRunner.query(`ALTER TABLE "sub_components" DROP CONSTRAINT "FK_520ce9d3c21e8c923594e41a9b4"`);
        await queryRunner.query(`ALTER TABLE "assessment_sub_components" DROP CONSTRAINT "FK_491f914eb689f85dacb625ec36d"`);
        await queryRunner.query(`ALTER TABLE "assessment_sub_components" DROP CONSTRAINT "FK_b8872c355bac08350b10674213e"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_90b881aab6a38f217baeb8f368c"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_a6aab0d30090866bb9cc0c61c72"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_5dec0f90b2df8ac2a78dc3ffa65"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_bed415cd29716cd707e9cb3c09c"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_b48a96c0b32fd72836304e87808"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_e0243bcb1acde5e1a8527b9d934"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_03d6ca091fc6902430e48d4b3ec"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_1bd66b7e0599333e61d2e3e1678"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_863462f942e7c32f90bc411617f"`);
        await queryRunner.query(`ALTER TABLE "roadmaps" DROP CONSTRAINT "FK_1654cfbc9ae5de0ea9d0789e51b"`);
        await queryRunner.query(`ALTER TABLE "roadmaps" DROP CONSTRAINT "FK_bf403fa995741d8fdab78c60b18"`);
        await queryRunner.query(`ALTER TABLE "roadmaps" DROP CONSTRAINT "FK_8029a1a5348e1af2ab284f2237f"`);
        await queryRunner.query(`ALTER TABLE "measurement_scale_descriptions" DROP CONSTRAINT "FK_e169341ffba51be4b4c9466f8ba"`);
        await queryRunner.query(`ALTER TABLE "measurement_scale_descriptions" DROP CONSTRAINT "FK_8c85013226083add8b763cb776d"`);
        await queryRunner.query(`ALTER TABLE "scales" DROP CONSTRAINT "FK_85bcf18557499c631fe04a38259"`);
        await queryRunner.query(`ALTER TABLE "assessment_members" DROP CONSTRAINT "FK_d50cfe323c72819e9b520ac6273"`);
        await queryRunner.query(`ALTER TABLE "assessment_members" DROP CONSTRAINT "FK_37ee2e3555f4d4d7da2ec2998ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f417b3a2e38339487716aa0742"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b70d6dbde0e342b2afd199490c"`);
        await queryRunner.query(`DROP TABLE "users_permissions_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21db462422f1f97519a29041da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deeb1fe94ce2d111a6695a2880"`);
        await queryRunner.query(`DROP TABLE "users_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f25fd350775094ceb3a02c1468"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf98d8fd47610db71dfc5a4a5f"`);
        await queryRunner.query(`DROP TABLE "roles_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79318fb026bf8e2a19a5f64d41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28ed803df963293de68d58e191"`);
        await queryRunner.query(`DROP TABLE "permissions_users_users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TYPE "public"."profiles_gender_enum"`);
        await queryRunner.query(`DROP TABLE "dashboard"`);
        await queryRunner.query(`DROP TYPE "public"."dashboard_assessmentstatus_enum"`);
        await queryRunner.query(`DROP TABLE "domains"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ee9fc4c57cce74443dca8d033"`);
        await queryRunner.query(`DROP TABLE "components"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_520ce9d3c21e8c923594e41a9b"`);
        await queryRunner.query(`DROP TABLE "sub_components"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_491f914eb689f85dacb625ec36"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8872c355bac08350b10674213"`);
        await queryRunner.query(`DROP TABLE "assessment_sub_components"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90b881aab6a38f217baeb8f368"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6aab0d30090866bb9cc0c61c7"`);
        await queryRunner.query(`DROP TABLE "assessments"`);
        await queryRunner.query(`DROP TYPE "public"."assessments_language_enum"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5dec0f90b2df8ac2a78dc3ffa6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bed415cd29716cd707e9cb3c09"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bd66b7e0599333e61d2e3e167"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_863462f942e7c32f90bc411617"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_863462f942e7c32f90bc411617"`);
        await queryRunner.query(`DROP TABLE "answers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8029a1a5348e1af2ab284f2237"`);
        await queryRunner.query(`DROP TABLE "roadmaps"`);
        await queryRunner.query(`DROP TABLE "measurements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e169341ffba51be4b4c9466f8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c85013226083add8b763cb776"`);
        await queryRunner.query(`DROP TABLE "measurement_scale_descriptions"`);
        await queryRunner.query(`DROP TABLE "scales"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d50cfe323c72819e9b520ac627"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d50cfe323c72819e9b520ac627"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37ee2e3555f4d4d7da2ec2998e"`);
        await queryRunner.query(`DROP TABLE "assessment_members"`);
        await queryRunner.query(`DROP TYPE "public"."assessment_members_role_enum"`);
        await queryRunner.query(`DROP TABLE "responses"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
