name: Test matrix output

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["i386", "arm64v8"]
    steps:
      - uses: actions/checkout@v3
      - id: build
        run: echo "image=example-image:${{ matrix.platform }}" >> $GITHUB_OUTPUT
      - uses: cloudposse/github-action-matrix-outputs-write@v1
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.platform }}
          outputs: |
            {"image":"example-image:${{ matrix.platform }}"}
  read:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: build
      - run: echo ${{ fromJson(steps.read.outputs.result) }}