services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: africa_cdc_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - africa_cdc_network
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-runner
      args:
        APP_NAME: hemat-api
    container_name: api
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - africa_cdc_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-runner
      args:
        APP_NAME: web
    container_name: web
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - africa_cdc_network

volumes:
  postgres_data:
    name: africa_cdc_postgres_data

networks:
  africa_cdc_network:
    driver: bridge