^terragrunt:
  GOOGLE_CREDENTIALS: file://config.json?query=.google_application_credentials
  GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT: file://config.json?query=.google_backend_impersonate_service_account
