export enum PermissionActionEnum {
  READ = 'read',
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  REMOVE = 'remove',
  RESTORE = 'restore',
  APPROVE = 'approve',
  REJECT = 'reject',
}
export enum PermissionSubjectEnum {
  ASSESSMENT = 'assessment',
  ASSESSMENT_ANSWER = 'assessment-answer',
  ASSESSMENT_COMPONENT = 'assessment-component',
  ASSESSMENT_DOMAIN = 'assessment-domain',
  ASSESSMENT_GROUP = 'assessment-group',
  ASSESSMENT_LANGUAGE = 'assessment-language',
  ASSESSMENT_MEASUREMENT_SCALE = 'assessment-measurement-scale',
  ASSESSMENT_MEASUREMENT_SCALE_SUB_COMPONENT = 'assessment-measurement-scale-sub-component',
  ASSESSMENT_MEMBER = 'assessment-member',
  ASSESSMENT_SUB_COMPONENT = 'assessment-sub-component',
  COMMENT = 'comment',
  COMPONENT = 'component',
  COUNTRY = 'country',
  DASHBOARD = 'dashboard',
  DOMAIN = 'domain',
  ENTITY = 'entity',
  INVITATION = 'invitation',
  LANGUAGE = 'language',
  MEASUREMENT_SCALE = 'measurement-scale',
  MEASUREMENT_SCALE_SUB_COMPONENT = 'measurement-scale-sub-component',
  PERMISSION = 'permission',
  PROFILE = 'profile',
  REPORT = 'report',
  RESPONSE = 'response',
  ROADMAP = 'roadmap',
  ROLE = 'role',
  SUB_COMPONENT = 'sub-component',
  USER = 'user',
  SUPPORT = 'support',
  SUPPORT_REPLY = 'support-reply',
}

export const ENTITY_CLASS_TO_PERMISSION_SUBJECT: Record<string, PermissionSubjectEnum> = {
  User: PermissionSubjectEnum.USER,
  Profile: PermissionSubjectEnum.PROFILE,
  Assessment: PermissionSubjectEnum.ASSESSMENT,
  AssessmentMember: PermissionSubjectEnum.ASSESSMENT_MEMBER,
  AssessmentGroup: PermissionSubjectEnum.ASSESSMENT_GROUP,
  AssessmentDomain: PermissionSubjectEnum.ASSESSMENT_DOMAIN,
  AssessmentComponent: PermissionSubjectEnum.ASSESSMENT_COMPONENT,
  AssessmentSubComponent: PermissionSubjectEnum.ASSESSMENT_SUB_COMPONENT,
  AssessmentMeasurementScale: PermissionSubjectEnum.ASSESSMENT_MEASUREMENT_SCALE,
  Answer: PermissionSubjectEnum.ASSESSMENT_ANSWER,
  Comment: PermissionSubjectEnum.COMMENT,
  Component: PermissionSubjectEnum.COMPONENT,
  Country: PermissionSubjectEnum.COUNTRY,
  Dashboard: PermissionSubjectEnum.DASHBOARD,
  Domain: PermissionSubjectEnum.DOMAIN,
  Invitation: PermissionSubjectEnum.INVITATION,
  Language: PermissionSubjectEnum.LANGUAGE,
  MeasurementScale: PermissionSubjectEnum.MEASUREMENT_SCALE,
  MeasurementScaleSubComponent: PermissionSubjectEnum.MEASUREMENT_SCALE_SUB_COMPONENT,
  Permission: PermissionSubjectEnum.PERMISSION,
  Report: PermissionSubjectEnum.REPORT,
  Response: PermissionSubjectEnum.RESPONSE,
  Roadmap: PermissionSubjectEnum.ROADMAP,
  Role: PermissionSubjectEnum.ROLE,
  SubComponent: PermissionSubjectEnum.SUB_COMPONENT,
  Support: PermissionSubjectEnum.SUPPORT,
  SupportReply: PermissionSubjectEnum.SUPPORT_REPLY,
};
