export const PERMISSION_FIELD_CONFIG = {
  baseFields: [
    'id',
    'action',
    'subject',
    'description',
    'createdAt',
    'updatedAt',
    'deletedAt',
  ],
  includeRelations: ['roles', 'users'],
  selectableFields: [
    'id',
    'action',
    'subject',
    'description',
    'createdAt',
    'updatedAt',
    'deletedAt',
    'roles.id',
    'roles.name',
    'users.id',
    'users.name',
    'users.email',
  ],
  searchableFields: ['action', 'subject', 'description'],
  filterableFields: [
    'action',
    'subject',
    'createdAt',
    'updatedAt',
    'deletedAt',
  ],
  sortableFields: ['action', 'subject', 'createdAt', 'updatedAt', 'deletedAt'],
};
