export const ROLE_FIELD_CONFIG = {
  baseFields: [
    'id',
    'name',
    'description',
    'createdAt',
    'updatedAt',
    'deletedAt',
  ],
  includeRelations: ['users', 'permissions'],
  selectableFields: [
    'id',
    'name',
    'description',
    'createdAt',
    'updatedAt',
    'deletedAt',
    'users.id',
    'users.name',
    'users.email',
    'permissions.id',
    'permissions.action',
    'permissions.subject',
    'permissions.description',
  ],
  searchableFields: ['name', 'description'],
  filterableFields: ['name', 'createdAt', 'updatedAt', 'deletedAt'],
  sortableFields: ['name', 'createdAt', 'updatedAt', 'deletedAt'],
};
