export const ASSESSMENT_FIELD_CONFIG = {
  includeRelations: [
    'user',
    'country',
    'domains',
    'components',
    'subComponents',
    'subComponents.measurementScales',
    'subComponents.measurementScales.measurementScale',
  ],
  selectableFields: [
    'id',
    'userId',
    'name',
    'description',
    'countryCode',
    'organization',
    'startDate',
    'endDate',
    'status',
    'languages',
    'createdAt',
    'updatedAt',
    'deletedAt',
    'user.id',
    'user.email',
    'user.name',
    'country.code',
    'country.name',
    'domains.id',
    'domains.code',
    'domains.name',
  ],
  searchableFields: ['name', 'description', 'organization', 'status'],
  filterableFields: ['userId', 'countryCode', 'startDate', 'endDate', 'status'],
  sortableFields: [
    'name',
    'startDate',
    'endDate',
    'status',
    'createdAt',
    'updatedAt',
  ],
  baseFields: [
    'id',
    'userId',
    'name',
    'description',
    'countryCode',
    'organization',
    'startDate',
    'endDate',
    'status',
    'languages',
    'createdAt',
    'updatedAt',
  ],
};