export const ASSESSMENT_FIELD_CONFIG = {
  includeRelations: ['user', 'country', 'domains'],
  selectableFields: [
    'id',
    'userId',
    'name',
    'description',
    'countryCode',
    'organization',
    'date',
    'domainId',
    'user.id',
    'user.email',
    'user.name',
    'country.code',
    'country.name',
    'domains.id',
    'domains.code',
    'domains.name',
  ],
  searchableFields: ['name', 'description'],
  filterableFields: ['countryCode', 'userId', 'domainId'],
  sortableFields: ['name', 'date'],
  baseFields: [
    'id',
    'userId',
    'name',
    'description',
    'countryCode',
    'organization',
    'date',
    'domainId',
  ],
};
