export const PartnersImages = [
  {
    src: "/images/partners/afenet.svg",
    width: 100,
    height: 50,
    alt: "cdc logo",
  },
  {
    src: "/images/partners/africa_public_health.svg",
    width: 100,
    height: 1000,
    alt: "africa public health logo",
  },
  {
    src: "/images/partners/african_dev_fund.svg",
    width: 100,
    height: 50,
    alt: "african dev fund logo",
  },
  {
    src: "/images/partners/cdc.svg",
    width: 100,
    height: 70,
    alt: "cdc logo",
  },
  {
    src: "/images/partners/giz_au.jpg",
    width: 150,
    height: 70,
    alt: "giz logo",
  },
  {
    src: "/images/partners/global_fund.svg",
    width: 200,
    height: 50,
    alt: "global fund logo",
  },
  {
    src: "/images/partners/jica.svg",
    width: 100,
    height: 50,
    alt: "jica logo",
  },
  {
    src: "/images/partners/london_school_of_hygiene.svg",
    width: 200,
    height: 50,
    alt: "london school of hygiene logo",
  },
  {
    src: "/images/partners/public_health_england.svg",
    width: 100,
    height: 50,
    alt: "public health england logo",
  },
  {
    src: "/images/partners/ukaid.svg",
    width: 100,
    height: 80,
    alt: "ukaid logo",
  },
  {
    src: "/images/partners/unaids.svg",
    width: 100,
    height: 120,
    alt: "unaids logo",
  },
  {
    src: "/images/partners/usaid.svg",
    width: 100,
    height: 50,
    alt: "usaid logo",
  },
  {
    src: "/images/partners/who.svg",
    width: 100,
    height: 100,
    alt: "who logo",
  },
  {
    src: "/images/partners/world_bank.svg",
    width: 100,
    height: 50,
    alt: "world bank logo",
  },
  {
    src: "/images/partners/zambia.svg",
    width: 100,
    height: 50,
    alt: "zambia",
  },
  {
    src: "/images/partners/tunisia.svg",
    width: 160,
    height: 160,
    alt: "tunisia",
  },
  {
    src: "/images/partners/republique_togo.svg",
    width: 100,
    height: 80,
    alt: "republique togo",
  },
  {
    src: "/images/partners/republic_of_seychelles.svg",
    width: 180,
    height: 180,
    alt: "republic of seychelles",
  },
  {
    src: "/images/partners/namibia.svg",
    width: 180,
    height: 180,
    alt: "namibia",
  },
  {
    src: "/images/partners/liberia.png",
    width: 100,
    height: 60,
    alt: "liberia",
  },
  {
    src: "/images/partners/kenya.png",
    width: 100,
    height: 100,
    alt: "kenya",
  },
  {
    src: "/images/partners/ivory_coast.svg",
    width: 120,
    height: 120,
    alt: "ivory coast",
  },
  {
    src: "/images/partners/ethiopia.svg",
    width: 100,
    height: 60,
    alt: "ethiopia",
  },
  {
    src: "/images/partners/cameron.svg",
    width: 100,
    height: 50,
    alt: "cameron",
  },
];

export const DomainIconMap: Record<string, string[]> = {
  "fluent-mdl2:party-leader": ["leadership", "governance"],
  "game-icons:satellite-communication": [
    "information",
    "communication",
    "technology",
  ],
  "carbon:ibm-knowledge-catalog-standard": ["standards", "interoperability"],
  "fluent-mdl2:workforce-management": ["management", "workspace"],
};
