name: Build and Deploy

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker.yaml
    with:
      artifact_registry_region: us-west1
      artifact_registry_host: docker.pkg.dev
      image_prefix: africa-cdc
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

  deploy:
    needs: build
    uses: ./.github/workflows/terragrunt.yaml
    with:
      deploy_dir: deploy/app/stg
      tf_args: "${{ needs.build.outputs.matrix_outputs }}"
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      USERNAME: ${{ secrets.HTTP_USERNAME }}
      TOKEN: ${{ secrets.HTTP_TOKEN }}